[workspace]
name = "rewire-viewer"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
channels = ["conda-forge"]
preview = ["pixi-build"]

[package]
name = "rewire-viewer"
version = "0.2.1"

[package.build]
backend = { name = "pixi-build-rust", version = "*", channels = ["https://prefix.dev/conda-forge"] }

[package.build.config]
extra-args = ["--bin", "rewire-viewer"]

[dependencies]

[tasks]
check = "cargo check"
fmt = "cargo fmt"
lint = "cargo clippy --all-features --all-targets -- -D warnings"
test = "cargo test"
sanity = { depends-on = ["check", "fmt", "lint", "test"] }
build = "cargo build --release"
build-wasm = { cmd = "cargo build --lib --target wasm32-unknown-unknown --release --no-default-features", env = { AR_wasm32_unknown_unknown = "llvm-ar", CC_wasm32_unknown_unknown = "clang" } }
check-wasm = { cmd = "cargo check --lib --target wasm32-unknown-unknown --no-default-features", env = { AR_wasm32_unknown_unknown = "llvm-ar", CC_wasm32_unknown_unknown = "clang" } }

[feature.dev.dependencies]
rust = ">=1.95"
rust-std-wasm32-unknown-unknown = "*"
rerun-sdk = ">=0.30"
compilers = "*"

[environments]
default = { features = ["dev"] }
